# Generated by Django 5.2.10 on 2026-08-19 03:14

import django.db.models.deletion
import ventas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0097_mensajewhatsappentrante_media_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Captador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('interno', 'Usuario interno'), ('empresa', 'Empresa existente'), ('externo', 'Organización externa')], max_length=20)),
                ('nombre_externo', models.CharField(blank=True, max_length=200)),
                ('tipo_organizacion', models.CharField(blank=True, choices=[('empresa', 'Empresa'), ('escuela', 'Escuela'), ('universidad', 'Universidad'), ('organizacion', 'Organización'), ('otro', 'Otro')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('desactivado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_desactivacion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captadores_creados', to=settings.AUTH_USER_MODEL)),
                ('desactivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captadores_desactivados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captador_ventas', to='clinica.empresa')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captador_ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tipo', 'id'],
                'permissions': [('manage_captadores', 'Puede administrar captadores'), ('view_codigo_propio', 'Puede consultar su propio código de captación'), ('validate_codigo', 'Puede validar códigos de captación')],
            },
        ),
        migrations.CreateModel(
            name='CodigoCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=ventas.models.generar_token_captacion, editable=False, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True)),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos', to='ventas.captador')),
            ],
            options={
                'ordering': ['-activo', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoCaptador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('desactivado', 'Desactivado'), ('reactivado', 'Reactivado')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ventas.captador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='captador',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('empresa__isnull', True), ('nombre_externo', ''), ('tipo', 'interno'), ('tipo_organizacion', ''), ('usuario__isnull', False)), models.Q(('empresa__isnull', False), ('nombre_externo', ''), ('tipo', 'empresa'), ('tipo_organizacion', ''), ('usuario__isnull', True)), models.Q(('empresa__isnull', True), ('tipo', 'externo'), ('usuario__isnull', True), models.Q(('nombre_externo', ''), _negated=True), models.Q(('tipo_organizacion', ''), _negated=True)), _connector='OR'), name='ventas_captador_identidad_coherente'),
        ),
        migrations.AddConstraint(
            model_name='codigocaptacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('captador',), name='ventas_un_codigo_activo_por_captador'),
        ),
    ]
