# Generated by Django 5.2.10 on 2026-08-19 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0097_mensajewhatsappentrante_media_id_and_more'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Captacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('canal', models.CharField(blank=True, max_length=50)),
                ('captador_nombre_snapshot', models.CharField(max_length=200)),
                ('captador_tipo_snapshot', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captaciones', to='ventas.captador')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captaciones', to='ventas.codigocaptacion')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='captacion_ventas', to='clinica.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_captacion', '-id'],
                'permissions': [('view_captaciones', 'Puede consultar captaciones'), ('register_captacion', 'Puede registrar captaciones')],
            },
        ),
        migrations.CreateModel(
            name='IntentoCaptacionRechazado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('atencion_previa', 'Atención previa'), ('ya_captado', 'Ya cuenta con captación')], max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_captacion_rechazados', to='clinica.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_captacion_rechazados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
