# Generated by Django 5.2.10 on 2026-08-19 14:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0097_mensajewhatsappentrante_media_id_and_more'),
        ('ventas', '0002_captacion_intentocaptacionrechazado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('captacion_aprobada', 'Captación aprobada'), ('captacion_rechazada', 'Captación rechazada')], max_length=30)),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20)),
                ('porcentaje_comision', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='captacion',
            options={'ordering': ['-fecha_captacion', '-id'], 'permissions': [('view_captaciones', 'Puede consultar captaciones'), ('register_captacion', 'Puede registrar captaciones'), ('review_captacion', 'Puede aprobar o rechazar captaciones')]},
        ),
        migrations.AddField(
            model_name='captacion',
            name='decidido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captacion',
            name='decidido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captaciones_decididas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='captacion',
            name='porcentaje_comision',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='captacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='captacion',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_comision__isnull', True), models.Q(('porcentaje_comision__gte', 1), ('porcentaje_comision__lte', 10)), _connector='OR'), name='ventas_captacion_porcentaje_1_10'),
        ),
        migrations.AddField(
            model_name='eventocaptacion',
            name='captacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ventas.captacion'),
        ),
        migrations.AddField(
            model_name='eventocaptacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_captacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
