# Generated by Django 5.2.10 on 2026-08-19 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0097_mensajewhatsappentrante_media_id_and_more'),
        ('ventas', '0003_eventocaptacion_alter_captacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captador_nombre_snapshot', models.CharField(max_length=200)),
                ('paciente_nombre_snapshot', models.CharField(max_length=200)),
                ('porcentaje_aplicado', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago')], default='pendiente_pago', max_length=20)),
                ('captacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comision', to='ventas.captacion')),
                ('cita_generadora', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comision_captacion_generada', to='clinica.cita')),
            ],
            options={
                'verbose_name': 'Comisión de captación',
                'verbose_name_plural': 'Comisiones de captación',
                'ordering': ['-generada_en', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje_aplicado__gte', 1), ('porcentaje_aplicado__lte', 10)), name='ventas_comision_porcentaje_1_10'), models.CheckConstraint(condition=models.Q(('base_calculo__gte', 0)), name='ventas_comision_base_no_negativa'), models.CheckConstraint(condition=models.Q(('monto_calculado__gte', 0)), name='ventas_comision_monto_no_negativo')],
            },
        ),
    ]
