# Generated by Django 5.2.10 on 2026-08-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_comisioncaptacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocaptacion',
            name='accion',
            field=models.CharField(choices=[('captacion_aprobada', 'Captación aprobada'), ('captacion_rechazada', 'Captación rechazada'), ('comision_generada', 'Comisión generada')], max_length=30),
        ),
    ]
