# Generated by Django 5.2.10 on 2026-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_eventocaptacion_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisioncaptacion',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('suspendida', 'Suspendida')], default='pendiente_pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventocaptacion',
            name='accion',
            field=models.CharField(choices=[('captacion_aprobada', 'Captación aprobada'), ('captacion_rechazada', 'Captación rechazada'), ('comision_generada', 'Comisión generada'), ('comision_suspendida', 'Comisión suspendida'), ('comision_reactivada', 'Comisión reactivada')], max_length=30),
        ),
    ]
