# Generated by Django 5.2.10 on 2026-08-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_comisioncaptacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisioncaptacion',
            options={'ordering': ['-generada_en', '-id'], 'permissions': [('view_comisiones_captacion', 'Puede consultar obligaciones por comisiones de captación')], 'verbose_name': 'Comisión de captación', 'verbose_name_plural': 'Comisiones de captación'},
        ),
    ]
