# Generated by Django 5.2.10 on 2026-08-20 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_comisioncaptacion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador')], default='borrador', max_length=20)),
                ('beneficiario_nombre_snapshot', models.CharField(max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('captador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_comisiones', to='ventas.captador')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_comisiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación de comisiones',
                'verbose_name_plural': 'Liquidaciones de comisiones',
                'ordering': ['-creada_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaLiquidacionComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('agregada_en', models.DateTimeField(auto_now_add=True)),
                ('agregada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_liquidacion_agregadas', to=settings.AUTH_USER_MODEL)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_liquidacion', to='ventas.comisioncaptacion')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='ventas.liquidacioncomisiones')),
            ],
            options={
                'verbose_name': 'Línea de liquidación de comisión',
                'verbose_name_plural': 'Líneas de liquidación de comisiones',
                'ordering': ['liquidacion_id', 'agregada_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('liquidacion_creada', 'Liquidación creada')], max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_liquidacion', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ventas.liquidacioncomisiones')),
            ],
            options={
                'verbose_name': 'Evento de liquidación',
                'verbose_name_plural': 'Eventos de liquidación',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='liquidacioncomisiones',
            index=models.Index(fields=['captador', 'estado'], name='ventas_liq_capt_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='linealiquidacioncomision',
            index=models.Index(fields=['liquidacion', 'activa'], name='ventas_linea_liq_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='linealiquidacioncomision',
            index=models.Index(fields=['comision', 'activa'], name='ventas_linea_com_activa_idx'),
        ),
        migrations.AddConstraint(
            model_name='linealiquidacioncomision',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('comision',), name='ventas_una_linea_activa_comision'),
        ),
        migrations.AddIndex(
            model_name='eventoliquidacion',
            index=models.Index(fields=['liquidacion', 'creado_en'], name='ventas_evento_liq_fecha_idx'),
        ),
    ]
