# Generated by Django 5.2.10 on 2026-08-20 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_liquidacioncomisiones_linealiquidacioncomision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacioncomisiones',
            options={'ordering': ['-creada_en', '-id'], 'permissions': [('view_liquidaciones', 'Puede consultar liquidaciones'), ('create_liquidacion', 'Puede crear liquidaciones'), ('change_draft_liquidacion', 'Puede modificar borradores de liquidación'), ('cancel_draft_liquidacion', 'Puede cancelar borradores de liquidación')], 'verbose_name': 'Liquidación de comisiones', 'verbose_name_plural': 'Liquidaciones de comisiones'},
        ),
        migrations.AddField(
            model_name='linealiquidacioncomision',
            name='motivo_retiro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linealiquidacioncomision',
            name='retirada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linealiquidacioncomision',
            name='retirada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_liquidacion_retiradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_comisiones_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventoliquidacion',
            name='accion',
            field=models.CharField(choices=[('liquidacion_creada', 'Liquidación creada'), ('comision_agregada', 'Comisión agregada'), ('comision_retirada', 'Comisión retirada'), ('borrador_cancelado', 'Borrador cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='liquidacioncomisiones',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
    ]
