# Generated by Django 5.2.10 on 2026-08-20 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_liquidacioncomisiones_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidacioncomisiones',
            options={'ordering': ['-creada_en', '-id'], 'permissions': [('view_liquidaciones', 'Puede consultar liquidaciones'), ('create_liquidacion', 'Puede crear liquidaciones'), ('change_draft_liquidacion', 'Puede modificar borradores de liquidación'), ('cancel_draft_liquidacion', 'Puede cancelar borradores de liquidación'), ('pay_liquidacion', 'Puede registrar pagos de liquidaciones')], 'verbose_name': 'Liquidación de comisiones', 'verbose_name_plural': 'Liquidaciones de comisiones'},
        ),
        migrations.AddField(
            model_name='linealiquidacioncomision',
            name='monto_liquidado_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='monto_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='pagada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='pagada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_comisiones_pagadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacioncomisiones',
            name='referencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventoliquidacion',
            name='accion',
            field=models.CharField(choices=[('liquidacion_creada', 'Liquidación creada'), ('comision_agregada', 'Comisión agregada'), ('comision_retirada', 'Comisión retirada'), ('borrador_cancelado', 'Borrador cancelado'), ('liquidacion_pagada', 'Liquidación pagada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='liquidacioncomisiones',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada')], default='borrador', max_length=20),
        ),
    ]
