# Generated by Django 5.2.10 on 2026-08-29 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_liquidacioncomisiones_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisioncaptacion',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('suspendida', 'Suspendida'), ('pagada', 'Pagada')], default='pendiente_pago', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('pagado_en', models.DateTimeField(auto_now_add=True)),
                ('comision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='ventas.comisioncaptacion')),
                ('pagado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_comisiones_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de comisión',
                'verbose_name_plural': 'Pagos de comisiones',
                'ordering': ['-pagado_en', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe_pagado__gte', 0)), name='ventas_pago_comision_importe_no_negativo')],
            },
        ),
    ]
