# Generated by Django 5.2.10 on 2026-08-31 04:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_comisioncaptacion_estado_pagocomision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codigocaptacion',
            name='porcentaje_comision',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='codigocaptacion',
            name='porcentaje_configurado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codigocaptacion',
            name='porcentaje_configurado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_captacion_porcentaje_configurados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='codigocaptacion',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_comision__isnull', True), models.Q(('porcentaje_comision__gte', 1), ('porcentaje_comision__lte', 10)), _connector='OR'), name='ventas_codigo_captacion_porcentaje_1_10'),
        ),
    ]
