# Generated by Django 5.2.10 on 2026-09-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_codigo_captacion_porcentaje_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigocaptacion',
            options={'ordering': ['-activo', '-creado_en'], 'permissions': [('authorize_captacion_commission', 'Puede autorizar o modificar la comisión de captación')]},
        ),
    ]
