# Generated by Django 5.2.10 on 2026-01-26 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono (WhatsApp)')),
                ('identidad_contacto', models.CharField(choices=[('propio', 'Propio'), ('madre', 'Madre'), ('padre', 'Padre'), ('pareja', 'Pareja'), ('otro', 'Otro')], default='propio', max_length=20)),
                ('consentimiento_firmado', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('estudio_socioeconomico', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('apertura_expediente', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('resumen_clinico', models.TextField(blank=True, null=True)),
                ('enlace_resultados', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pacientes_relacionados', models.ManyToManyField(blank=True, to='clinica.paciente')),
                ('servicio_inicial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicio', verbose_name='Servicio Inicial')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('costo', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Terminal', 'Terminal'), ('Pase', 'Pase'), ('Gratuito', 'Gratuito'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20)),
                ('estatus', models.CharField(choices=[('programada', 'Programada'), ('asistio', 'Asistió'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20)),
                ('folio_fiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.consultorio')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.division')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.paciente')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicio')),
                ('terapeuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
