# Generated by Django 5.2.10 on 2026-01-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre_normalizado',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
