# Generated by Django 5.2.10 on 2026-02-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_sede_alter_cita_options_rename_hora_cita_hora_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receta', 'Receta Médica'), ('estudio', 'Estudio/Análisis'), ('radiografia', 'Radiografía'), ('consentimiento', 'Consentimiento Informado'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_documento', models.DateField()),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('cirugias_previas', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura en cm', max_digits=5, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expediente Médico',
                'verbose_name_plural': 'Expedientes Médicos',
            },
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='servicio_inicial',
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['sede__nombre', 'nombre'], 'verbose_name': 'Consultorio', 'verbose_name_plural': 'Consultorios'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='terapeuta',
            options={'ordering': ['nombre'], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='notas',
            new_name='notas_pago',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_registro',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='resumen_clinico',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apertura_expediente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='consentimiento_firmado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='enlace_resultados',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estudio_socioeconomico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='identidad_contacto',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pacientes_relacionados',
        ),
        migrations.AddField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='capacidad',
            field=models.IntegerField(default=1, help_text='Número de personas que puede atender simultáneamente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='color_calendario',
            field=models.CharField(default='#3788d8', help_text='Color en formato hexadecimal para el calendario', max_length=7),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'terapeuta'], name='clinica_cit_fecha_f70556_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='clinica_cit_pacient_bf01cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='clinica_cit_estado_83390f_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['nombre_normalizado'], name='clinica_pac_nombre__e2ad02_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['telefono'], name='clinica_pac_telefon_378ffd_idx'),
        ),
        migrations.AddField(
            model_name='documentopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clinica.paciente'),
        ),
        migrations.AddField(
            model_name='expedientemedico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='clinica.paciente'),
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
