# Generated by Django 5.2.10 on 2026-02-12 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_documentopaciente_expedientemedico_delete_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentopaciente',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='expedientemedico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='consultorio',
            name='sede',
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='consultorio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='terapeuta',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='clinica_cit_fecha_f70556_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='clinica_cit_pacient_bf01cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='clinica_cit_estado_83390f_idx',
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='clinica_pac_nombre__e2ad02_idx',
        ),
        migrations.RemoveIndex(
            model_name='paciente',
            name='clinica_pac_telefon_378ffd_idx',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='hora_fin',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='notas_pago',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='creado_en',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='direccion',
            new_name='resumen_clinico',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='consultorio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='consultorio',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_emergencia',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='color_calendario',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cita',
            name='estatus',
            field=models.CharField(choices=[('programada', 'Programada'), ('asistio', 'Asistió'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='folio_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apertura_expediente',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_firmado',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enlace_resultados',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estudio_socioeconomico',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identidad_contacto',
            field=models.CharField(choices=[('propio', 'Propio'), ('madre', 'Madre'), ('padre', 'Padre'), ('pareja', 'Pareja'), ('otro', 'Otro')], default='propio', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pacientes_relacionados',
            field=models.ManyToManyField(blank=True, to='clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.consultorio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Terminal', 'Terminal'), ('Pase', 'Pase'), ('Gratuito', 'Gratuito'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='terapeuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.terapeuta'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=20, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default=1, max_length=20, verbose_name='Teléfono (WhatsApp)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.division'),
        ),
        migrations.AddField(
            model_name='horario',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.terapeuta'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='servicio_inicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicio', verbose_name='Servicio Inicial'),
        ),
        migrations.DeleteModel(
            name='DocumentoPaciente',
        ),
        migrations.DeleteModel(
            name='ExpedienteMedico',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
