# Generated by Django 5.2.10 on 2026-02-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_division_horario_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
