# Generated by Django 5.2.10 on 2026-02-18 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_paciente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_deseada', models.DateField()),
                ('hora_deseada', models.TimeField(blank=True, null=True)),
                ('notas_paciente', models.TextField(blank=True, help_text='Mensaje original del paciente', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Razón enviada al paciente si se rechaza', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.terapeuta')),
            ],
        ),
    ]
