# Generated by Django 5.2.10 on 2026-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_solicitudcita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='pacientes',
            field=models.ManyToManyField(related_name='citas_grupo', to='clinica.paciente'),
        ),
    ]
