# Generated by Django 5.2.10 on 2026-03-11 17:26

from django.db import migrations, models


def normalizar_estatus_citas(apps, schema_editor):
    Cita = apps.get_model('clinica', 'Cita')

    mapeo = {
        'programada': 'sin_confirmar',
        'asistio': 'confirmada',
        'cancelada': 'cancelo',
    }

    for origen, destino in mapeo.items():
        Cita.objects.filter(estatus=origen).update(estatus=destino)


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_cita_pacientes_adicionales'),
    ]

    operations = [
        migrations.RunPython(normalizar_estatus_citas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cita',
            name='estatus',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('sin_confirmar', 'Sin confirmar'), ('reagendo', 'Reagendo'), ('cancelo', 'Cancelo'), ('no_asistio', 'No asistio'), ('incidencia', 'Incidencia')], default='sin_confirmar', max_length=20),
        ),
    ]
