# Generated by Django 5.2.10 on 2026-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_alter_cita_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_paciente',
            field=models.CharField(choices=[('N', 'Nuevo'), ('R', 'Referido'), ('S', 'Seguimiento')], default='S', max_length=1),
        ),
    ]
