# Generated by Django 5.2.10 on 2026-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_crear_terapeuta_rosa_maria_gomez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estatus',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('sin_confirmar', 'Sin confirmar'), ('reagendo', 'Reagendo'), ('cancelo', 'Cancelo'), ('si_asistio', 'Si asistio'), ('no_asistio', 'No asistio'), ('incidencia', 'Incidencia')], default='sin_confirmar', max_length=20),
        ),
    ]
