# Generated by Django 5.2.10 on 2026-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0018_alter_cita_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Pase', 'Pase')], max_length=50, null=True),
        ),
    ]
