# Generated by Django 5.2.10 on 2026-03-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0019_alter_cita_metodo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabuladorGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de categoría (0 al 11).', unique=True)),
                ('descripcion', models.TextField(help_text='Perfil de formación que corresponde a esta categoría.')),
                ('pago_base', models.DecimalField(decimal_places=2, help_text='Monto fijo por sesión en consultorio INTRA.', max_digits=8)),
                ('pago_consultorio_propio', models.DecimalField(blank=True, decimal_places=2, help_text='Monto alternativo si la sesión es en consultorio del terapeuta (cats. 6 y 11).', max_digits=8, null=True)),
                ('bono_monto', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del bono al alcanzar el umbral de pacientes.', max_digits=8, null=True)),
                ('bono_umbral_pacientes', models.IntegerField(blank=True, help_text='Número de pacientes semanales necesarios para activar el bono (repetible).', null=True)),
            ],
            options={
                'verbose_name': 'Tabulador General',
                'verbose_name_plural': 'Tabulador General',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CorteSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Lunes de la semana del corte.')),
                ('fecha_fin', models.DateField(help_text='Domingo de la semana del corte.')),
                ('total_sesiones', models.IntegerField(default=0)),
                ('subtotal_sesiones', models.DecimalField(decimal_places=2, default=0, help_text='Suma de pagos por sesión (sin bonos).', max_digits=10)),
                ('total_bonos', models.DecimalField(decimal_places=2, default=0, help_text='Suma de todos los bonos del periodo.', max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, help_text='Total a pagar: subtotal_sesiones + total_bonos.', max_digits=10)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado')], default='borrador', max_length=20)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortes_semanales', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Corte Semanal',
                'verbose_name_plural': 'Cortes Semanales',
                'ordering': ['-fecha_inicio', 'terapeuta'],
                'unique_together': {('terapeuta', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='BonoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text="Descripción del pago manual (ej. 'Hora de elaboración de informe — evaluación neuropsicológica').", max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, help_text='Cita relacionada al bono, si aplica (ej. la evaluación que generó la hora extra).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.cita')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Staff o admin que autorizó este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonos_extra_registrados', to=settings.AUTH_USER_MODEL)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonos_extra', to='clinica.cortesemanal')),
            ],
            options={
                'verbose_name': 'Bono Extra',
                'verbose_name_plural': 'Bonos Extra',
            },
        ),
        migrations.CreateModel(
            name='LineaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sesion', 'Sesión'), ('bono_umbral', 'Bono por volumen'), ('bono_por_paciente', 'Bono por paciente')], default='sesion', max_length=30)),
                ('concepto', models.CharField(help_text='Descripción legible del concepto calculado.', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cita', models.ForeignKey(blank=True, help_text='Nulo únicamente en líneas de bono global (bono de volumen).', null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.cita')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='clinica.cortesemanal')),
            ],
            options={
                'verbose_name': 'Línea de Nómina',
                'verbose_name_plural': 'Líneas de Nómina',
            },
        ),
        migrations.CreateModel(
            name='ReglaTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_por_sesion', models.DecimalField(blank=True, decimal_places=2, help_text='Monto único para cualquier tipo de sesión. Usar cuando el terapeuta cobra igual sin importar modalidad.', max_digits=8, null=True)),
                ('pago_individual', models.DecimalField(blank=True, decimal_places=2, help_text='Pago para sesiones individuales cuando hay tarifa diferenciada por modalidad.', max_digits=8, null=True)),
                ('pago_pareja', models.DecimalField(blank=True, decimal_places=2, help_text='Pago para sesiones de pareja o familiar cuando hay tarifa diferenciada.', max_digits=8, null=True)),
                ('pago_consultorio_propio', models.DecimalField(blank=True, decimal_places=2, help_text='Monto cuando la cita se realiza en el consultorio propio del terapeuta (médicos).', max_digits=8, null=True)),
                ('bono_umbral_monto', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del bono que se paga por cada vez que se alcanza el umbral de pacientes.', max_digits=8, null=True)),
                ('bono_umbral_pacientes', models.IntegerField(blank=True, help_text='Cantidad de pacientes para activar el bono de volumen (ej: 5 → bono por cada 5 pacientes).', null=True)),
                ('bono_por_paciente', models.DecimalField(blank=True, decimal_places=2, help_text='Bono fijo adicional por cada paciente atendido en el corte (ej: bono supervisor de $25/paciente).', max_digits=8, null=True)),
                ('notas', models.TextField(blank=True, help_text="Observaciones operativas (ej: 'reportar hora extra en evaluaciones').")),
                ('terapeuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regla_pago', to='clinica.terapeuta')),
                ('tabulador_base', models.ForeignKey(blank=True, help_text='Categoría del tabulador general como referencia. Opcional si se usan montos individualizados.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.tabuladorgeneral')),
            ],
            options={
                'verbose_name': 'Regla de Pago (Terapeuta)',
                'verbose_name_plural': 'Reglas de Pago (Terapeutas)',
            },
        ),
    ]
