# Generated by Django 5.2.10 on 2026-03-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0021_crear_servicio_evaluacion_psicologica_infantil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgendaTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bloqueo', models.CharField(choices=[('temporal', 'Temporal'), ('permanente', 'Permanente')], default='temporal', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_terapeutas_creados', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Bloqueo de Agenda del Terapeuta',
                'verbose_name_plural': 'Bloqueos de Agenda de Terapeutas',
                'ordering': ['fecha_inicio', '-creado_en'],
            },
        ),
    ]
