# Generated by Django 5.2.10 on 2026-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0022_bloqueoagendaterapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueoagendaterapeuta',
            name='alcance',
            field=models.CharField(choices=[('fecha', 'Fecha específica'), ('dia_semana', 'Día semanal')], default='fecha', max_length=20),
        ),
        migrations.AddField(
            model_name='bloqueoagendaterapeuta',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='bloqueoagendaterapeuta',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloqueoagendaterapeuta',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
