# Generated by Django 5.2.10 on 2026-03-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0023_bloqueoagendaterapeuta_alcance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaTerapeutaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_terapeutas', to='clinica.paciente')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_pacientes', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Nota de Terapeuta por Paciente',
                'verbose_name_plural': 'Notas de Terapeutas por Paciente',
                'ordering': ['-creado_en'],
            },
        ),
    ]
