# Generated by Django 5.2.10 on 2026-03-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0025_alter_notaterapeutapaciente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('consentimiento', 'Consentimiento'), ('estudio', 'Estudio socioeconomico'), ('apertura', 'Apertura de expediente'), ('resultado', 'Resultado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(upload_to='documentos_pacientes_historial/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='clinica.paciente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_pacientes_subidos', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_pacientes_subidos', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Documento de Paciente',
                'verbose_name_plural': 'Documentos de Pacientes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
