# Generated by Django 5.2.10 on 2026-03-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0026_documentopaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentopaciente',
            name='archivo',
        ),
        migrations.AddField(
            model_name='documentopaciente',
            name='contenido',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='documentopaciente',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentopaciente',
            name='tipo_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
