# Generated by Django 5.2.10 on 2026-03-25 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0028_solicitudcita_consultorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_sesion', models.PositiveIntegerField(default=1, verbose_name='# De sesión')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de finalización')),
                ('objetivo_sesion', models.TextField(blank=True, verbose_name='Objetivo de la sesión')),
                ('revision_tareas', models.TextField(blank=True, verbose_name='Revisión de tareas')),
                ('desarrollo_sesion', models.TextField(blank=True, verbose_name='Desarrollo de sesión')),
                ('tecnicas_utilizadas', models.TextField(blank=True, verbose_name='Técnicas utilizadas')),
                ('resultados_sesion', models.TextField(blank=True, verbose_name='Resultados de la sesión')),
                ('tareas', models.TextField(blank=True, verbose_name='Tareas')),
                ('comentarios_finales', models.TextField(blank=True, verbose_name='Comentarios Finales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporte_sesion', to='clinica.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_sesion', to='clinica.paciente')),
                ('terapeuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_sesion', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Reporte de Sesión',
                'verbose_name_plural': 'Reportes de Sesión',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
