# Generated by Django 5.2.10 on 2026-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0031_crear_servicio_evaluacion_psicologica'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='sede',
            field=models.CharField(blank=True, choices=[('republica', 'República'), ('morelos', 'Morelos'), ('colinas', 'Colinas'), ('trabajo_social', 'Trabajo Social'), ('zoom', 'Zoom / Online'), ('externo', 'Externo')], max_length=20, null=True),
        ),
    ]
