# Generated by Django 5.2.10 on 2026-03-31 19:12

from django.db import migrations, models


def poblar_sedes_consultorio(apps, schema_editor):
    Consultorio = apps.get_model('clinica', 'Consultorio')
    reglas = [
        ('república', 'republica'),
        ('republica',  'republica'),
        ('morelos',    'morelos'),
        ('colinas',    'colinas'),
        ('trabajo social', 'trabajo_social'),
        ('zoom',       'zoom'),
        ('externo',    'externo'),
    ]
    for c in Consultorio.objects.all():
        nombre_lower = c.nombre.lower()
        for keyword, sede_key in reglas:
            if keyword in nombre_lower:
                c.sede = sede_key
                c.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0032_horario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='sede',
            field=models.CharField(blank=True, choices=[('republica', 'República'), ('morelos', 'Morelos'), ('colinas', 'Colinas'), ('trabajo_social', 'Trabajo Social'), ('zoom', 'Zoom / Online'), ('externo', 'Externo')], max_length=20, null=True),
        ),
        migrations.RunPython(poblar_sedes_consultorio, migrations.RunPython.noop),
    ]
