# Generated by Django 5.2.10 on 2026-04-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0034_empresa_paciente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='clinica.division'),
        ),
    ]
