# Generated by Django 5.2.10 on 2026-04-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0035_empresa_add_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.division'),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='clinica.empresa'),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='clinica.paciente'),
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.servicio'),
        ),
    ]
