# Generated by Django 5.2.10 on 2026-04-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0036_solicitudcita_campos_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReagendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_propuesta', models.DateField()),
                ('hora_propuesta', models.TimeField()),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('nota_recepcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reagendo', to='clinica.cita')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reagendo', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Solicitud de Reagendo',
                'verbose_name_plural': 'Solicitudes de Reagendo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
