# Generated by Django 6.0.3 on 2026-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0039_accesodirectoportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tiene_descuento',
            field=models.BooleanField(blank=True, help_text='Indica si el paciente tiene descuento / estudio socioeconómico activo al momento de la cita.', null=True),
        ),
    ]
