# Generated by Django 5.2.10 on 2026-04-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0040_cita_tiene_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio público del servicio. Se usa para calcular penalizaciones por inasistencia.', max_digits=10, null=True, verbose_name='Precio estándar'),
        ),
        migrations.CreateModel(
            name='PenalizacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita_cobro', models.ForeignKey(blank=True, help_text='Cita en la que se cobró la penalización.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalizacion_cobrada', to='clinica.cita')),
                ('cita_origen', models.OneToOneField(help_text='Cita de inasistencia que generó esta penalización.', on_delete=django.db.models.deletion.CASCADE, related_name='penalizacion_generada', to='clinica.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Penalización por Inasistencia',
                'verbose_name_plural': 'Penalizaciones por Inasistencia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
