# Generated by Django 5.2.10 on 2026-04-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0043_corregir_precios_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineanomina',
            name='tipo',
            field=models.CharField(choices=[('sesion', 'Sesión'), ('bono_umbral', 'Bono por volumen'), ('bono_por_paciente', 'Bono por paciente'), ('penalizacion', 'Penalización inasistencia')], default='sesion', max_length=30),
        ),
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('queja', 'Queja'), ('sugerencia', 'Sugerencia'), ('incidente', 'Incidente en consultorio')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_incidente', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Reporte / Incidente',
                'verbose_name_plural': 'Reportes e Incidentes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
