# Generated by Django 6.0.3 on 2026-04-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0044_reporte_incidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='No. de Expediente')),
                ('tipo', models.CharField(choices=[('pareja', 'Pareja'), ('familia', 'Familia')], default='pareja', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=300, verbose_name='Nombre del Expediente')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.division')),
                ('pacientes', models.ManyToManyField(blank=True, related_name='expedientes_grupales', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Expediente Grupal',
                'verbose_name_plural': 'Expedientes Grupales',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='expediente_grupal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.expedientegrupal'),
        ),
        migrations.CreateModel(
            name='NotaExpedienteGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='clinica.expedientegrupal')),
                ('terapeuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_expedientes_grupales', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Nota de Expediente Grupal',
                'verbose_name_plural': 'Notas de Expediente Grupal',
                'ordering': ['-creado_en'],
            },
        ),
    ]
