# Generated by Django 6.0.3 on 2026-04-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0045_expedientegrupal_cita_expediente_grupal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaExpedienteGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('calle', models.CharField(blank=True, max_length=200, verbose_name='Calle')),
                ('num_exterior', models.CharField(blank=True, max_length=20, verbose_name='Núm.')),
                ('colonia', models.CharField(blank=True, max_length=150, verbose_name='Col.')),
                ('religion', models.CharField(blank=True, max_length=100, verbose_name='Religión')),
                ('vive_con', models.CharField(blank=True, max_length=200, verbose_name='Vive con')),
                ('tiene_hijos', models.BooleanField(default=False, verbose_name='Tiene hijos')),
                ('num_hijos', models.PositiveIntegerField(blank=True, null=True, verbose_name='No. de Hijos')),
                ('hijo_1', models.CharField(blank=True, max_length=200, verbose_name='Hijo 1')),
                ('hijo_2', models.CharField(blank=True, max_length=200, verbose_name='Hijo 2')),
                ('hijo_3', models.CharField(blank=True, max_length=200, verbose_name='Hijo 3')),
                ('hijo_4', models.CharField(blank=True, max_length=200, verbose_name='Hijo 4')),
                ('emergencia_contacto', models.CharField(blank=True, max_length=200, verbose_name='En caso de emergencia llamar a')),
                ('emergencia_telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de emergencia')),
                ('como_se_entero', models.CharField(blank=True, max_length=200, verbose_name='¿Cómo se enteraron de nosotros?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.division', verbose_name='División')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apertura', to='clinica.expedientegrupal')),
            ],
            options={
                'verbose_name': 'Apertura de Expediente Grupal',
                'verbose_name_plural': 'Aperturas de Expediente Grupal',
            },
        ),
    ]
