# Generated by Django 6.0.3 on 2026-04-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0046_aperturaexpedientegrupal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='clinica.division', verbose_name='División'),
        ),
    ]
