# Generated by Django 6.0.3 on 2026-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0047_paciente_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortesemanal',
            name='confirmacion_terapeuta',
            field=models.CharField(blank=True, choices=[('aceptado', 'Aceptado por terapeuta'), ('incidencia', 'Incidencia reportada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cortesemanal',
            name='confirmacion_terapeuta_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
