# Generated by Django 5.2.10 on 2026-04-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def crear_usuario_host(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Host = apps.get_model('clinica', 'Host')

    user, created = User.objects.get_or_create(
        username='carlos.host',
        defaults={
            'password': make_password('host123'),
            'is_active': True,
            'is_staff': False,
            'is_superuser': False,
        },
    )
    if not created:
        user.password = make_password('host123')
        user.is_active = True
        user.save(update_fields=['password', 'is_active'])

    Host.objects.get_or_create(
        usuario=user,
        defaults={
            'nombre': 'Carlos Host',
            'activo': True,
        },
    )


def eliminar_usuario_host(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    Host = apps.get_model('clinica', 'Host')

    Host.objects.filter(usuario__username='carlos.host').delete()
    User.objects.filter(username='carlos.host').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0048_confirmacion_terapeuta_nomina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.RunPython(crear_usuario_host, eliminar_usuario_host),
    ]
