# Generated by Django 5.2.10 on 2026-04-28 19:35

from django.db import migrations, models


def crear_tareas_base(apps, schema_editor):
    HostChecklistTask = apps.get_model('clinica', 'HostChecklistTask')
    tareas = [
        ('Revisar agenda del consultorio', 'Confirmar citas, horarios y terapeutas', 'Prioritario', True, 10),
        ('Preparar recepcion', 'Verificar ambiente, limpieza y acceso', 'Ambiente', False, 20),
        ('Recibir pacientes programados', 'Confirmar nombre, horario y terapeuta', 'Citas', False, 30),
        ('Avisar cambios de agenda', 'Reportar retrasos o cancelaciones', 'Alerta', True, 40),
        ('Completar video-capacitacion', 'Modulo host en curso', 'Formacion', False, 50),
        ('Cierre de consultorio', 'Dejar notas internas y pendientes', 'Admin', False, 60),
    ]
    for titulo, subtitulo, etiqueta, urgente, orden in tareas:
        HostChecklistTask.objects.get_or_create(
            titulo=titulo,
            defaults={
                'subtitulo': subtitulo,
                'etiqueta': etiqueta,
                'urgente': urgente,
                'orden': orden,
                'activo': True,
            },
        )


def eliminar_tareas_base(apps, schema_editor):
    HostChecklistTask = apps.get_model('clinica', 'HostChecklistTask')
    HostChecklistTask.objects.filter(
        titulo__in=[
            'Revisar agenda del consultorio',
            'Preparar recepcion',
            'Recibir pacientes programados',
            'Avisar cambios de agenda',
            'Completar video-capacitacion',
            'Cierre de consultorio',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0049_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('subtitulo', models.CharField(blank=True, max_length=180)),
                ('etiqueta', models.CharField(blank=True, max_length=40)),
                ('urgente', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.ManyToManyField(blank=True, help_text='Dejalo vacio para que aplique a todos los hosts.', related_name='tareas_checklist', to='clinica.host')),
            ],
            options={
                'verbose_name': 'Tarea de Checklist Host',
                'verbose_name_plural': 'Tareas de Checklist Host',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RunPython(crear_tareas_base, eliminar_tareas_base),
    ]
