# Generated by Django 5.2.10 on 2026-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0050_hostchecklisttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='actividad_fisica',
            field=models.BooleanField(default=False, verbose_name='¿Realiza actividad física?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='comidas_al_dia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Comidas al día'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='consume_alcohol',
            field=models.BooleanField(default=False, verbose_name='¿Consume alcohol?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='consume_otras_sustancias',
            field=models.BooleanField(default=False, verbose_name='¿Consume o ha consumido otras sustancias?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='cual_actividad_fisica',
            field=models.CharField(blank=True, max_length=200, verbose_name='¿Cuál actividad física?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='cual_enfermedad',
            field=models.CharField(blank=True, max_length=300, verbose_name='¿Cuál enfermedad?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='cuales_sustancias',
            field=models.CharField(blank=True, max_length=300, verbose_name='¿Cuáles sustancias?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='fuma',
            field=models.BooleanField(default=False, verbose_name='¿Fuma?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='ha_tomado_terapia',
            field=models.BooleanField(default=False, verbose_name='¿Ha tomado terapia anteriormente?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='horas_sueno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de sueño al día'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='intento_suicida',
            field=models.BooleanField(default=False, verbose_name='¿Ha intentado quitarse la vida?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='intento_suicida_hace_cuanto',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Hace cuánto? (Intento)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='intento_suicida_motivo',
            field=models.TextField(blank=True, verbose_name='¿Por qué?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='intento_suicida_que_hizo',
            field=models.TextField(blank=True, verbose_name='¿Qué hizo?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='terapia_duracion',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Cuánto duró la terapia?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='terapia_hace_cuanto',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Hace cuánto? (Terapia)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='terapia_motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de la terapia anterior'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tiene_enfermedad',
            field=models.BooleanField(default=False, verbose_name='¿Tiene alguna enfermedad?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tx_psiquiatrico',
            field=models.BooleanField(default=False, verbose_name='¿Está o ha estado en tratamiento psiquiátrico?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tx_psiquiatrico_hace_cuanto',
            field=models.CharField(blank=True, max_length=100, verbose_name='¿Hace cuánto? (Tx psiquiátrico)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tx_psiquiatrico_medicamento',
            field=models.CharField(blank=True, max_length=300, verbose_name='Medicamento(s)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tx_psiquiatrico_motivo',
            field=models.TextField(blank=True, verbose_name='Motivo del tratamiento psiquiátrico'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='vida_sexual_activa',
            field=models.BooleanField(default=False, verbose_name='¿Tiene vida sexual activa?'),
        ),
    ]
