# Generated by Django 5.2.10 on 2026-04-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0051_apertura_expediente_antecedentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoPropio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del recurso')),
                ('descripcion', models.CharField(blank=True, max_length=400, verbose_name='Descripción')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('contenido', models.BinaryField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_propios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso Propio',
                'verbose_name_plural': 'Recursos Propios',
                'ordering': ['nombre'],
            },
        ),
    ]
