# Generated by Django 5.2.10 on 2026-05-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0052_recurso_propio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita_aceptada', 'Cita aceptada'), ('cita_rechazada', 'Cita rechazada'), ('reagendo_aprobado', 'Reagendo aprobado'), ('reagendo_rechazado', 'Reagendo rechazado')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Notificación de Terapeuta',
                'verbose_name_plural': 'Notificaciones de Terapeutas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
