# Generated by Django 5.2.10 on 2026-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0053_notificacion_terapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionterapeuta',
            name='tipo',
            field=models.CharField(choices=[('cita_aceptada', 'Cita aceptada'), ('cita_rechazada', 'Cita rechazada'), ('cita_modificada', 'Cita modificada'), ('reagendo_aprobado', 'Reagendo aprobado'), ('reagendo_rechazado', 'Reagendo rechazado')], max_length=30),
        ),
    ]
