# Generated by Django 6.0.3 on 2026-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0054_notificacion_tipo_modificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcita',
            name='tipo_paciente',
            field=models.CharField(blank=True, choices=[('N', 'Nuevo'), ('R', 'Referido'), ('S', 'Seguimiento')], default='S', max_length=1),
        ),
    ]
