# Generated by Django 6.0.3 on 2026-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0055_solicitudcita_tipo_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcita',
            name='tipo_paciente',
        ),
        migrations.AddField(
            model_name='solicitudcita',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('pareja', 'Pareja'), ('familiar', 'Familiar'), ('grupal', 'Grupal')], default='individual', max_length=20),
        ),
    ]
