# Generated by Django 6.0.3 on 2026-05-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0056_solicitudcita_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcita',
            name='modalidad',
        ),
    ]
