# Generated by Django 6.0.3 on 2026-05-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0057_solicitudcita_remove_modalidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_recepcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Recepción',
                'verbose_name_plural': 'Notas de Recepción',
                'ordering': ['-creado_en'],
            },
        ),
    ]
