# Generated by Django 6.0.3 on 2026-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0059_reaccion_comentario_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteincidente',
            name='respuesta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='respuesta_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacionterapeuta',
            name='tipo',
            field=models.CharField(choices=[('cita_aceptada', 'Cita aceptada'), ('cita_rechazada', 'Cita rechazada'), ('cita_modificada', 'Cita modificada'), ('reagendo_aprobado', 'Reagendo aprobado'), ('reagendo_rechazado', 'Reagendo rechazado'), ('respuesta_incidente', 'Respuesta a reporte')], max_length=30),
        ),
    ]
