# Generated by Django 6.0.3 on 2026-05-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0060_respuesta_incidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('titulo', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría')], default='Licenciatura', max_length=20)),
                ('cedula', models.CharField(blank=True, default='Sin cédula registrada', max_length=200)),
                ('preparacion', models.TextField(blank=True)),
                ('formacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('terapeuta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_catalogo', to='clinica.terapeuta')),
            ],
            options={
                'verbose_name': 'Perfil Catálogo',
                'verbose_name_plural': 'Perfiles Catálogo',
                'ordering': ['nombre'],
            },
        ),
    ]
