# Generated by Django 6.0.3 on 2026-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0067_seed_actividad_historica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tipo_paciente',
            field=models.CharField(choices=[('N', 'Nuevo'), ('R', 'Referido'), ('S', 'Seguimiento'), ('C', 'Crisis')], default='S', max_length=1),
        ),
    ]
