# Generated by Django 5.2.10 on 2026-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0069_consultoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoria',
            name='divisiones',
            field=models.ManyToManyField(blank=True, help_text='Divisiones a las que esta consultoria tiene acceso.', related_name='consultorias', to='clinica.division'),
        ),
    ]
