# Generated by Django 5.2.10 on 2026-06-08 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0071_seed_consultoria_tsdt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del instrumento')),
                ('clave', models.SlugField(help_text="Identificador interno usado por el motor de puntuación (ej. 'preconsulta', 'scid_ii').", unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / para qué sirve')),
                ('instrucciones', models.TextField(blank=True, help_text='Texto que ve el paciente antes de empezar a responder.', verbose_name='Instrucciones para el paciente')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EnvioInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondido', 'Respondido'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('interpretacion', models.TextField(blank=True, help_text='Texto de interpretación generado por el motor de puntuación a partir del baremo del instrumento.', verbose_name='Interpretación automática')),
                ('resultado_detalle', models.JSONField(blank=True, help_text='Desglose del cálculo (subescalas, rangos, semáforos, etc.) que respalda la interpretación automática.', null=True, verbose_name='Detalle del resultado')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumentos_generados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos_enviados', to='clinica.paciente')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='clinica.instrumento')),
            ],
            options={
                'verbose_name': 'Aplicación de Instrumento',
                'verbose_name_plural': 'Aplicaciones de Instrumento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('clave', models.CharField(blank=True, help_text="Identificador interno del reactivo para el motor de puntuación (ej. 'item_1').", max_length=50)),
                ('tipo_respuesta', models.CharField(choices=[('opcion_unica', 'Opción única'), ('opcion_multiple', 'Opción múltiple'), ('escala', 'Escala numérica / Likert'), ('si_no', 'Sí / No'), ('texto_libre', 'Texto libre')], default='opcion_unica', max_length=20)),
                ('opciones', models.JSONField(blank=True, help_text='Opciones de respuesta como lista de objetos {valor, etiqueta}. Aplica a opción única/múltiple/escala.', null=True)),
                ('requerida', models.BooleanField(default=True)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='clinica.instrumento')),
            ],
            options={
                'verbose_name': 'Pregunta de Instrumento',
                'verbose_name_plural': 'Preguntas de Instrumento',
                'ordering': ['instrumento', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, verbose_name='Respuesta cruda (texto u opción elegida)')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, help_text='Equivalente numérico de la respuesta, usado por el motor de puntuación.', max_digits=8, null=True, verbose_name='Valor numérico')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='clinica.envioinstrumento')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='clinica.preguntainstrumento')),
            ],
            options={
                'verbose_name': 'Respuesta de Instrumento',
                'verbose_name_plural': 'Respuestas de Instrumento',
                'ordering': ['envio', 'pregunta__orden'],
                'unique_together': {('envio', 'pregunta')},
            },
        ),
    ]
