# Generated by Django 5.2.10 on 2026-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0072_instrumento_envioinstrumento_preguntainstrumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='accion',
            field=models.CharField(choices=[('cita_creada', 'Cita agendada'), ('cita_editada', 'Cita editada'), ('cita_eliminada', 'Cita eliminada'), ('cita_checkout', 'Sesión cerrada'), ('disponib_agregada', 'Disponibilidad agregada'), ('disponib_eliminada', 'Disponibilidad eliminada'), ('bloqueo_creado', 'Bloqueo de agenda creado'), ('bloqueo_eliminado', 'Bloqueo de agenda eliminado'), ('solicitud_aceptada', 'Solicitud aceptada'), ('solicitud_rechazada', 'Solicitud rechazada'), ('reagendo_solicitado', 'Reagendo solicitado'), ('reagendo_aprobado', 'Reagendo aprobado'), ('reagendo_rechazado', 'Reagendo rechazado'), ('paciente_registrado', 'Paciente registrado'), ('paciente_editado', 'Paciente editado'), ('paciente_eliminado', 'Paciente eliminado'), ('nomina_aprobada', 'Nómina aprobada'), ('expositor_respondido', 'Horas expositor respondidas'), ('incidente_reportado', 'Incidente reportado'), ('incidente_respondido', 'Incidente respondido'), ('instrumento_enviado', 'Instrumento enviado a paciente')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='categoria',
            field=models.CharField(choices=[('cita', 'Cita'), ('disponibilidad', 'Disponibilidad'), ('reagendo', 'Reagendo'), ('paciente', 'Paciente'), ('nomina', 'Nómina'), ('solicitud', 'Solicitud'), ('incidente', 'Incidente'), ('instrumento', 'Instrumento')], db_index=True, max_length=20),
        ),
    ]
