# Generated by Django 5.2.10 on 2026-06-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0073_alter_registroactividad_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntainstrumento',
            name='imagen',
            field=models.CharField(blank=True, default='', help_text="Ruta relativa a MEDIA_ROOT para la imagen de la pregunta (e.g. 'instrumentos/raven/1.png').", max_length=400),
        ),
        migrations.AlterField(
            model_name='preguntainstrumento',
            name='tipo_respuesta',
            field=models.CharField(choices=[('opcion_unica', 'Opción única'), ('opcion_multiple', 'Opción múltiple'), ('escala', 'Escala numérica / Likert'), ('si_no', 'Sí / No'), ('texto_libre', 'Texto libre'), ('imagen_unica', 'Imagen + opción única')], default='opcion_unica', max_length=20),
        ),
    ]
