# Generated by Django 5.2.10 on 2026-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0074_pregunta_instrumento_imagen_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntainstrumento',
            name='titulo_grupo',
            field=models.CharField(blank=True, default='', help_text='Encabezado de grupo para preguntas que se renderizan en bloque (e.g. ítem Allport S2).', max_length=600),
        ),
    ]
