# Generated by Django 5.2.10 on 2026-06-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0076_cita_encuesta_enviada_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatizacion_activa', models.BooleanField(default=True, help_text='Si está desactivado, el cron diario no envía recordatorios, confirmaciones ni encuestas; solo queda disponible el envío manual.')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
    ]
