# Generated by Django 6.0.3 on 2026-06-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0077_configuracionwhatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsAppEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=100, unique=True)),
                ('wa_id', models.CharField(max_length=20, verbose_name='Número (formato Meta)')),
                ('texto', models.TextField(blank=True)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('atendido_en', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp_recibidos', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp recibido',
                'verbose_name_plural': 'Mensajes WhatsApp recibidos',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
