# Generated by Django 6.0.3 on 2026-06-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0078_mensaje_whatsapp_entrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
