# Generated by Django 5.2.10 on 2026-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0079_mensaje_whatsapp_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dado_de_alta',
            field=models.BooleanField(default=False, verbose_name='Dado de alta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
