# Generated by Django 6.0.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0080_paciente_dado_de_alta_paciente_fecha_alta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeWhatsAppDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campana', models.CharField(help_text='Prospecto/cliente de la demo, ej. "dorothea"', max_length=50)),
                ('tipo', models.CharField(help_text='Clave de la plantilla de Meta enviada', max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_contacto', models.CharField(blank=True, max_length=150)),
                ('texto', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('respuesta_api', models.JSONField(blank=True, null=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp Demo',
                'verbose_name_plural': 'Mensajes WhatsApp Demo',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
