# Generated by Django 5.2.10 on 2026-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0080_respuestainstrumento_dado_de_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestainstrumento',
            name='dado_de_alta',
        ),
        migrations.RemoveField(
            model_name='respuestainstrumento',
            name='fecha_alta',
        ),
        migrations.AddField(
            model_name='paciente',
            name='dado_de_alta',
            field=models.BooleanField(default=False, verbose_name='Dado de alta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
