# Generated by Django 5.2.10 on 2026-07-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0081_paciente_estado_paciente_fecha_suspension_and_more'),
        ('clinica', '0081_remove_respuestainstrumento_dado_de_alta_and_more'),
    ]

    operations = [
    ]
