# Generated by Django 5.2.10 on 2026-07-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0081_mensajewhatsappdemo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Pase', 'Pase')], max_length=50, null=True),
        ),
    ]
