# Generated by Django 5.2.10 on 2026-07-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0081_paciente_estado_paciente_fecha_suspension_and_more'),
        ('clinica', '0082_alter_cita_metodo_pago'),
    ]

    operations = [
    ]
