# Generated by Django 5.2.10 on 2026-07-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ('clinica', '0082_alter_cita_metodo_pago'),

        ('clinica', '0082_merge_20260708_0955'),

    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='suspendido',
            field=models.BooleanField(default=False),
        ),
    ]
