# Generated by Django 5.2.10 on 2026-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0084_remove_paciente_suspendido_paciente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntainstrumento',
            name='imagen',
            field=models.CharField(blank=True, default='', help_text="Ruta relativa a static para la imagen de la pregunta (e.g. 'instrumentos/raven/1.png').", max_length=400),
        ),
    ]
