# Generated by Django 6.0.6 on 2026-07-22 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0086_grupo_direccion_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('divisiones', models.ManyToManyField(blank=True, help_text='Divisiones a las que este perfil de dirección comercial tiene acceso.', related_name='direcciones_comerciales', to='clinica.division')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_direccion_comercial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección Comercial',
                'verbose_name_plural': 'Dirección Comercial',
            },
        ),
    ]
