# Generated by Django 6.0.6 on 2026-07-24 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0090_seed_lider_operaciones_clinicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_supervisor_seguimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor de Seguimiento',
                'verbose_name_plural': 'Supervisores de Seguimiento',
            },
        ),
    ]
