# Generated by Django 6.0.6 on 2026-07-28 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0094_seed_benja_administrativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, help_text='10 dígitos, sin lada de país (mismo formato que Paciente.telefono).', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('suscrito', models.BooleanField(default=True, help_text='Si es False, el contacto pidió la baja y se excluye de toda campaña.')),
                ('baja_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto Academia',
                'verbose_name_plural': 'Contactos Academia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampanaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('plantilla_meta', models.CharField(help_text='Nombre exacto de la plantilla aprobada en Meta.', max_length=120)),
                ('idioma', models.CharField(default='es_MX', max_length=10)),
                ('texto_render', models.TextField(blank=True, help_text='Copia del cuerpo de la plantilla al momento de crear la campaña.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviando', 'Enviando'), ('enviada', 'Enviada'), ('pausada', 'Pausada')], default='borrador', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña masiva',
                'verbose_name_plural': 'Campañas masivas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddField(
            model_name='mensajewhatsappentrante',
            name='contacto_academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_recibidos', to='clinica.contactoacademia'),
        ),
        migrations.CreateModel(
            name='EnvioMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, help_text='ID que devuelve Meta al enviar; correlaciona los webhooks de estado.', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('error_codigo', models.CharField(blank=True, max_length=20)),
                ('error_mensaje', models.TextField(blank=True)),
                ('respuesta_api', models.JSONField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='clinica.campanamasiva')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='clinica.contactoacademia')),
            ],
            options={
                'verbose_name': 'Envío masivo',
                'verbose_name_plural': 'Envíos masivos',
                'ordering': ['contacto__nombre'],
                'unique_together': {('campana', 'contacto')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomado', models.CharField(max_length=120)),
                ('anio_fuente', models.IntegerField()),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('por_confirmar', 'Por confirmar')], default='activo', max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fila_origen', models.IntegerField(blank=True, help_text='Columna "Fila en archivo original" del Excel, para rastrear el dato.', null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='clinica.contactoacademia')),
            ],
            options={
                'verbose_name': 'Inscripción Academia',
                'verbose_name_plural': 'Inscripciones Academia',
                'ordering': ['-anio_fuente', 'diplomado'],
                'unique_together': {('contacto', 'diplomado', 'anio_fuente')},
            },
        ),
    ]
