# Generated by Django 6.0.6 on 2026-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0096_respuestamasiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsappentrante',
            name='media_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del archivo en Meta. Vacío si el mensaje es solo texto.', max_length=200),
        ),
        migrations.AddField(
            model_name='mensajewhatsappentrante',
            name='media_mime',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mensajewhatsappentrante',
            name='media_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mensajewhatsappentrante',
            name='media_tipo',
            field=models.CharField(blank=True, help_text='image, video, audio, document o sticker (tipos de la Cloud API).', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestamasiva',
            name='media_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del archivo en Meta. Vacío si el mensaje es solo texto.', max_length=200),
        ),
        migrations.AddField(
            model_name='respuestamasiva',
            name='media_mime',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='respuestamasiva',
            name='media_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='respuestamasiva',
            name='media_tipo',
            field=models.CharField(blank=True, help_text='image, video, audio, document o sticker (tipos de la Cloud API).', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestamasiva',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
