# Generated by Django 5.2.10 on 2026-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0096_respuestamasiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='curp',
            field=models.CharField(blank=True, max_length=20, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='escolaridad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Escolaridad'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='genero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='lateralidad',
            field=models.CharField(blank=True, choices=[('', '---------'), ('diestro', 'Diestro'), ('zurdo', 'Zurdo'), ('ambidiestro', 'Ambidiestro')], max_length=100, verbose_name='Lateralidad'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', '---------'), ('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], max_length=20, verbose_name='Sexo'),
        ),
    ]
