# Generated by Django 5.2.10 on 2026-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0097_aperturaexpediente_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
