# Generated by Django 5.2.10 on 2026-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0098_aperturaexpediente_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], max_length=20, verbose_name='Sexo'),
        ),
    ]
