# Generated by Django 5.2.10 on 2026-08-20 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0098_codigoinstitucionalpaciente'),
        ('ventas', '0010_alter_liquidacioncomisiones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineanomina',
            name='comision_captacion',
            field=models.OneToOneField(blank=True, help_text='Comisión histórica que origina esta línea. Sólo se utiliza para líneas de comisión de captación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linea_nomina', to='ventas.comisioncaptacion'),
        ),
        migrations.AlterField(
            model_name='lineanomina',
            name='tipo',
            field=models.CharField(choices=[('sesion', 'Sesión'), ('bono_umbral', 'Bono por volumen'), ('bono_por_paciente', 'Bono por paciente'), ('penalizacion', 'Penalización inasistencia'), ('expositor', 'Horas Expositor'), ('comision_captacion', 'Comisión de captación')], default='sesion', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='lineanomina',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cita__isnull', True), ('comision_captacion__isnull', False), ('tipo', 'comision_captacion')), models.Q(models.Q(('tipo', 'comision_captacion'), _negated=True), ('comision_captacion__isnull', True)), _connector='OR'), name='clinica_linea_nomina_comision_coherente'),
        ),
    ]
