# Generated by Django 5.2.10 on 2026-08-21 04:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0099_lineanomina_comision_captacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='descuento_captacion_porcentaje_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Descuento histórico de captación aplicado al servicio.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cita',
            name='importe_servicio_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe histórico del servicio usado como base de comisión. No representa dinero recibido.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='cita',
            name='precio_servicio_base_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio público histórico de referencia del servicio.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='MovimientoEconomicoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cobro', 'Cobro registrado por Recepción')], default='cobro', max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('registrado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='confirmado', max_length=20)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('clave_idempotencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_economicos_anulados', to=settings.AUTH_USER_MODEL)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_economicos', to='clinica.cita')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_economicos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento económico de cita',
                'verbose_name_plural': 'Movimientos económicos de citas',
                'ordering': ['-registrado_en', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='clinica_movimiento_importe_positivo'), models.CheckConstraint(condition=models.Q(models.Q(('anulado_en__isnull', True), ('anulado_por__isnull', True), ('estado', 'confirmado'), ('motivo_anulacion', '')), models.Q(('anulado_en__isnull', False), ('anulado_por__isnull', False), ('estado', 'anulado')), _connector='OR'), name='clinica_movimiento_anulacion_consistente')],
            },
        ),
    ]
