# Generated by Django 5.2.10 on 2026-07-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0099_alter_aperturaexpediente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='trabajo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar de Trabajo'),
        ),
    ]
