# Generated by Django 5.2.10 on 2026-07-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0100_aperturaexpediente_trabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturaexpediente',
            old_name='trabajo',
            new_name='nacimiento',
        ),
    ]
