# Generated by Django 5.2.10 on 2026-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0101_rename_trabajo_aperturaexpediente_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='nacimiento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar de Nacimiento'),
        ),
    ]
