# Generated by Django 5.2.10 on 2026-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0102_alter_aperturaexpediente_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='religion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Religión/Creencias'),
        ),
    ]
