# Generated by Django 5.2.10 on 2026-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0103_alter_aperturaexpediente_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='correo',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Correo electrónico'),
        ),
    ]
