# Generated by Django 5.2.10 on 2026-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0104_aperturaexpediente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='referido',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referido por'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('', '---------'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=20, verbose_name='Tipo de sangre'),
        ),
    ]
