# Generated by Django 5.2.10 on 2026-08-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0105_aperturaexpediente_referido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='acompanante_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del acompañante'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='confiabilidad_acompanante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Confiabilidad del informante'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='parentesco_acompanante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parentesco del acompañante'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='telefono_acompanante',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del acompañante'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='viene_acompanante',
            field=models.CharField(blank=True, max_length=200, verbose_name='¿Viene acompañado?'),
        ),
    ]
