# Generated by Django 5.2.10 on 2026-08-27 04:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0106_propuestas_tarifas_notificaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaBeneficioReferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Descuento')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_beneficio_referido_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('categoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_beneficio_referido', to='clinica.categoriaservicio', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_beneficio_referido_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de beneficio por referido',
                'verbose_name_plural': 'Reglas de beneficio por referido',
                'ordering': ('categoria_servicio__orden', '-vigente_desde', '-pk'),
                'permissions': [('view_referral_benefit_rule', 'Puede consultar reglas de beneficio por referido'), ('manage_referral_benefit_rule', 'Puede administrar reglas de beneficio por referido')],
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje_descuento__gte', Decimal('0.00')), ('porcentaje_descuento__lte', Decimal('100.00'))), name='regla_beneficio_porcentaje_entre_0_100'), models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gte', models.F('vigente_desde')), _connector='OR'), name='regla_beneficio_fin_no_anterior_inicio')],
            },
        ),
    ]
