# Generated by Django 5.2.10 on 2026-08-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0106_aperturaexpediente_acompanante_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='viene_acompanante',
            field=models.BooleanField(default=False, verbose_name='¿Viene acompañado?'),
        ),
    ]
