# Generated by Django 5.2.10 on 2026-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0107_alter_aperturaexpediente_viene_acompanante'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='padecimiento_actual',
            field=models.TextField(blank=True, verbose_name='Padecimiento actual'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parentesco del contacto de emergencia'),
        ),
    ]
