# Generated by Django 5.2.10 on 2026-08-28 04:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0107_reglabeneficioreferido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_esperado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cobro', to='clinica.cita')),
            ],
            options={
                'verbose_name': 'Cobro de cita',
                'verbose_name_plural': 'Cobros de citas',
                'ordering': ('-creado_en', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('importe_esperado__gte', Decimal('0.00'))), name='cobro_cita_importe_esperado_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_reportado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('metodo_pago', models.CharField(choices=[('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Pase', 'Pase')], max_length=50)),
                ('origen_registro', models.CharField(choices=[('terapeuta', 'Terapeuta'), ('recepcion', 'Recepción')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de verificación'), ('confirmado', 'Confirmado'), ('con_diferencia', 'Con diferencia'), ('anulado', 'Anulado')], default='pendiente_verificacion', max_length=30)),
                ('registrado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('importe_verificado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('observacion_diferencia', models.TextField(blank=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_anulados', to=settings.AUTH_USER_MODEL)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clinica.cobrocita')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-registrado_en', '-id'),
                'indexes': [models.Index(fields=['estado', 'registrado_en'], name='pago_estado_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe_reportado__gte', Decimal('0.00'))), name='pago_importe_reportado_no_negativo'), models.CheckConstraint(condition=models.Q(('importe_verificado__isnull', True), ('importe_verificado__gte', Decimal('0.00')), _connector='OR'), name='pago_importe_verificado_no_negativo'), models.UniqueConstraint(condition=models.Q(('origen_registro', 'terapeuta'), models.Q(('estado', 'anulado'), _negated=True)), fields=('cobro',), name='pago_checkout_terapeuta_activo_unico')],
            },
        ),
    ]
