# Generated by Django 5.2.10 on 2026-09-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0108_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobrocita',
            options={'ordering': ('-creado_en', '-id'), 'permissions': [('view_reception_ledger', 'Puede consultar la Bitácora de Recepción')], 'verbose_name': 'Cobro de cita', 'verbose_name_plural': 'Cobros de citas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ('-registrado_en', '-id'), 'permissions': [('register_reception_payment', 'Puede registrar pagos desde Recepción'), ('confirm_reception_payment', 'Puede confirmar pagos desde Recepción')], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
