# Generated by Django 5.2.10 on 2026-08-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0108_aperturaexpediente_padecimiento_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='fam_antecedentes',
            field=models.CharField(blank=True, choices=[('', '---------'), ('diabetes', 'Diabetes'), ('hta', 'HTA'), ('cardiopatias', 'Cardiopatías'), ('cancer', 'Cáncer'), ('epilepsia', 'Epilepsia'), ('trast_psiquiatricos', 'Trast psiquiátricos'), ('adicciones', 'Adicciones'), ('suicidios', 'Suicidios'), ('neuroogicos', 'Neurológicos')], max_length=100, verbose_name='Familiares con antecedentes'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='otros_antecedentes',
            field=models.TextField(blank=True, verbose_name='Otros antecedentes'),
        ),
    ]
