# Generated by Django 5.2.10 on 2026-08-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0097_mensajewhatsappentrante_media_id_and_more'),
        ('clinica', '0109_aperturaexpediente_fam_antecedentes_and_more'),
    ]

    operations = [
    ]
