# Generated by Django 5.2.10 on 2026-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0110_merge_20260805_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='fam_antecedentes',
            field=models.TextField(blank=True, verbose_name='Familiares con antecedentes'),
        ),
    ]
