# Generated by Django 5.2.10 on 2026-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0111_alter_aperturaexpediente_fam_antecedentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='act_fisica_sueño',
            field=models.TextField(blank=True, verbose_name='Actividad física / sueño'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='alimentacion',
            field=models.TextField(blank=True, verbose_name='Alimentación'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='det_conusmo',
            field=models.TextField(blank=True, verbose_name='Detalle de consumo de sustancias'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='hig_viv_servicios',
            field=models.TextField(blank=True, verbose_name='Higiene / vivienda / servicios'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='inmunizaciones',
            field=models.TextField(blank=True, verbose_name='Inmunizaciones'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='taxicomanias',
            field=models.TextField(blank=True, verbose_name='Toxicomanías'),
        ),
    ]
