# Generated by Django 5.2.10 on 2026-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0112_aperturaexpediente_act_fisica_sueño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='act_fisica_sueño',
            field=models.CharField(blank=True, max_length=300, verbose_name='Actividad física / sueño'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='alimentacion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Alimentación'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='det_conusmo',
            field=models.CharField(blank=True, max_length=300, verbose_name='Detalle de consumo de sustancias'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='hig_viv_servicios',
            field=models.CharField(blank=True, max_length=300, verbose_name='Higiene / vivienda / servicios'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='inmunizaciones',
            field=models.CharField(blank=True, max_length=300, verbose_name='Inmunizaciones'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='taxicomanias',
            field=models.CharField(blank=True, max_length=300, verbose_name='Toxicomanías'),
        ),
    ]
