# Generated by Django 5.2.10 on 2026-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0113_alter_aperturaexpediente_act_fisica_sueño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='det_conusmo',
            field=models.TextField(blank=True, verbose_name='Detalle de consumo de sustancias'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='fam_antecedentes',
            field=models.TextField(blank=True, verbose_name='Familiares con antecedentes (marque y especifique parentesco)'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='taxicomanias',
            field=models.TextField(blank=True, verbose_name='Toxicomanías'),
        ),
    ]
