# Generated by Django 5.2.10 on 2026-08-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0114_alter_aperturaexpediente_det_conusmo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='antecedentes_patologicos',
            field=models.TextField(blank=True, verbose_name='Antecedentes'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='detalle_diagnostico',
            field=models.TextField(blank=True, verbose_name='Detalle'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='diagnostico_previos',
            field=models.TextField(blank=True, verbose_name='Diagnósticos previos'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='medicacion_actual',
            field=models.TextField(blank=True, verbose_name='Medicación actual'),
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Medicamento')),
                ('dosis', models.CharField(blank=True, max_length=100, verbose_name='Dosis')),
                ('frecuencia', models.CharField(blank=True, max_length=100, verbose_name='Frecuencia')),
                ('observaciones', models.CharField(blank=True, max_length=300, verbose_name='Observaciones')),
                ('apertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='clinica.aperturaexpediente')),
            ],
            options={
                'verbose_name': 'Medicación',
                'verbose_name_plural': 'Medicaciones',
                'ordering': ['id'],
            },
        ),
    ]
