# Generated by Django 5.2.10 on 2026-08-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0115_aperturaexpediente_antecedentes_patologicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='det_conusmo',
            field=models.TextField(blank=True, verbose_name='Detalle de consumo (sustancias, cantidad, frecuencia, tiempo de evolución, último consumo):'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='motivo_consulta',
            field=models.TextField(blank=True, verbose_name='Motivo de consulta (en palabras del paciente / informante)'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='otros_antecedentes',
            field=models.TextField(blank=True, verbose_name='Especificaciones y otros antecedentes relevantes'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='padecimiento_actual',
            field=models.TextField(blank=True, verbose_name='Padecimiento actual (inicio, evolución, factores precipitantes, agravantes y atenuentes, tratamientos previos, repercusión funcional):'),
        ),
    ]
