# Generated by Django 5.2.10 on 2026-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0116_alter_aperturaexpediente_det_conusmo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='complicaiones',
            field=models.CharField(blank=True, max_length=300, verbose_name='Complicaciones perinatales'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='control_esfinteres',
            field=models.CharField(blank=True, max_length=300, verbose_name='Control de esfínteres'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='desempeño_escolar',
            field=models.TextField(blank=True, verbose_name='Desempeño escolar, conducta, estructura y dinámica familiar, red de apoyo:'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='embararazo_actual',
            field=models.BooleanField(default=False, verbose_name='¿Está embarazada actualmente?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='embarazo',
            field=models.CharField(blank=True, verbose_name='Embarazo (planeado, control, complicaciones)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='gestas',
            field=models.CharField(blank=True, null=True, verbose_name='Gestas / Partos / Cesáreas / Abortos'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='lactancia_actual',
            field=models.BooleanField(default=False, verbose_name='¿Está lactando actualmente?'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='menarca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Menarca'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='met_planificacin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Método de planificación'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='peso_nacer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso y talla al nacer (kg)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='primeras_palabras',
            field=models.CharField(blank=True, max_length=300, verbose_name='Primeras palabras / lenguaje'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='ritmo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ritmo / FUM'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='socializacion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Socialización'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sosten_cefalico',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sostén cefálico / sedestación / marcha'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tipo_parto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipo de parto / semanas de gestación'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='antecedentes_patologicos',
            field=models.CharField(blank=True, verbose_name='Antecedentes'),
        ),
    ]
