# Generated by Django 5.2.10 on 2026-08-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0117_aperturaexpediente_complicaiones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='desempeño_escolar',
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='abdomen',
            field=models.TextField(blank=True, verbose_name='Abdomen'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='cabeza_cuello',
            field=models.TextField(blank=True, verbose_name='Cabeza y cuello'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='dolor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dolor (0-10)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='exploracion_neurologica',
            field=models.TextField(blank=True, verbose_name='Exploración neurológica básica'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='extremidades',
            field=models.TextField(blank=True, verbose_name='Extremidades'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True, verbose_name='FC (lpm)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True, verbose_name='FR (rpm)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='genitales',
            field=models.TextField(blank=True, verbose_name='Genitales (cuando aplique)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='glucosa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Glucosa (mg/dL)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='habitus_exterior',
            field=models.TextField(blank=True, verbose_name='Habitus exterior'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='IMC'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='otros_signos_vitales',
            field=models.CharField(blank=True, max_length=300, verbose_name='Otros'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='perimetro_cefalico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perím. cefálico (cm)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='SatO₂ (%)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_cardiovascular',
            field=models.TextField(blank=True, verbose_name='Cardiovascular'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_digestivo',
            field=models.TextField(blank=True, verbose_name='Digestivo'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_endocrino',
            field=models.TextField(blank=True, verbose_name='Endocrino'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_genitourinario',
            field=models.TextField(blank=True, verbose_name='Genitourinario'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_hematologico',
            field=models.TextField(blank=True, verbose_name='Hematológico'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_musculoesqueletico',
            field=models.TextField(blank=True, verbose_name='Musculoesquelético'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_neurologico',
            field=models.TextField(blank=True, verbose_name='Neurológico'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_piel',
            field=models.TextField(blank=True, verbose_name='Piel y faneras'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_respiratorio',
            field=models.TextField(blank=True, verbose_name='Respiratorio'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sistema_sentidos',
            field=models.TextField(blank=True, verbose_name='Órganos de los sentidos'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='talla_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Talla (m)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp. (°C)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='tension_arterial',
            field=models.CharField(blank=True, max_length=20, verbose_name='T/A (mmHg)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='torax',
            field=models.TextField(blank=True, verbose_name='Tórax (cardiopulmonar)'),
        ),
    ]
