# Generated by Django 5.2.10 on 2026-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0118_remove_aperturaexpediente_desempeño_escolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='afecto_animo',
            field=models.TextField(blank=True, verbose_name='Afecto y estado de ánimo'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='aspecto_actitud',
            field=models.TextField(blank=True, verbose_name='Aspecto y actitud'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='atencion_concentracion',
            field=models.TextField(blank=True, verbose_name='Atención y concentración'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='conciencia_orientacion',
            field=models.TextField(blank=True, verbose_name='Conciencia y orientación'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='conductual',
            field=models.TextField(blank=True, verbose_name='Conductual'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='contencion',
            field=models.TextField(blank=True, verbose_name='Plan de seguridad / Contención (cuando aplique):'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='emocional_afectiva',
            field=models.TextField(blank=True, verbose_name='Emocional / Afectiva'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='escolar_laboral',
            field=models.TextField(blank=True, verbose_name='Escolar / Laboral'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='heteroagresion',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=100, verbose_name='Heteroagresión'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='ideacion',
            field=models.CharField(blank=True, choices=[('ausente', 'Ausente'), ('pasiva', 'Pasiva'), ('activa', 'Activa'), ('plan', 'Con plan'), ('intento', 'Antecedente de intento')], max_length=100, verbose_name='Ideación / Conducta suicida'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='juicio',
            field=models.TextField(blank=True, verbose_name='Juicio e introspección (insight)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='lenguaje',
            field=models.TextField(blank=True, verbose_name='Lenguaje'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='memoria',
            field=models.TextField(blank=True, verbose_name='Memoria'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='pensamiento',
            field=models.TextField(blank=True, verbose_name='Pensamiento (curso/contenido)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='personalidad',
            field=models.TextField(blank=True, verbose_name='Personalidad / Afrontamiento'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='psicomoticidad',
            field=models.TextField(blank=True, verbose_name='Psicomotricidad'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='sensopercepcion',
            field=models.TextField(blank=True, verbose_name='Sensopercepción'),
        ),
    ]
