# Generated by Django 5.2.10 on 2026-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0119_aperturaexpediente_afecto_animo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='heteroagresion',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=100, verbose_name='Riesgo de auto / heteroagresión'),
        ),
    ]
