# Generated by Django 5.2.10 on 2026-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0120_alter_aperturaexpediente_heteroagresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='analisis_cualitativo',
            field=models.TextField(blank=True, verbose_name='Analisis cualitativo e integración del perfil neuropsicológico:'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='atencion',
            field=models.TextField(blank=True, verbose_name='Atención (sostenida, selectiva, alternante)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='cognicion_social',
            field=models.TextField(blank=True, verbose_name='Cognición social'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='funciones_ejecutivas',
            field=models.TextField(blank=True, verbose_name='Funciones ejecutivas (planeación, inhibición, felxibilidad)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='gnosias',
            field=models.TextField(blank=True, verbose_name='Gnosias (visuales, táctiles, auditivas)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='habilidades_academicas',
            field=models.TextField(blank=True, verbose_name='Cálculo y habilidades académicas'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='habilidades_viso',
            field=models.TextField(blank=True, verbose_name='Habilidades visoespaciales'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='lenguaje_neuro',
            field=models.TextField(blank=True, verbose_name='Lenguaje (expresivo/comprensivo)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='memoria_trabajo',
            field=models.TextField(blank=True, verbose_name='Memoria de trabajo'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='memoria_verbal',
            field=models.TextField(blank=True, verbose_name='Memoria verbal'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='memoria_visual',
            field=models.TextField(blank=True, verbose_name='Memoria visual'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='orientacion',
            field=models.TextField(blank=True, verbose_name='Orientación'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='praxias',
            field=models.TextField(blank=True, verbose_name='Praxias (ideomotora, construccional)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='velocidad',
            field=models.TextField(blank=True, verbose_name='Velocidad de procesamiento'),
        ),
    ]
