# Generated by Django 5.2.10 on 2026-08-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0121_aperturaexpediente_analisis_cualitativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='cedula_profesional',
            field=models.TextField(blank=True, verbose_name='Cédula profesional'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='clinica_integradora',
            field=models.TextField(blank=True, verbose_name='Resumen e impresión clínica integradora:'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='diagnostico_diferencial',
            field=models.TextField(blank=True, verbose_name='Diagnóstico diferencial'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='duracion_estimada',
            field=models.TextField(blank=True, verbose_name='Duración estimada del tratamiento'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='factores_contextuales',
            field=models.TextField(blank=True, verbose_name='Factores contextuales / psicosociales'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='factores_pronostico',
            field=models.TextField(blank=True, verbose_name='Justificación de factores que modifican el pronóstico:'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='nivel_funcionamiento',
            field=models.TextField(blank=True, verbose_name='Nivel de funcionamiento (WHODAS / GAF)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='nombre_profesional',
            field=models.TextField(blank=True, verbose_name='Nombre del profesional'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='objetivos_terapeuticos',
            field=models.TextField(blank=True, verbose_name='Objetivos terapéuticos, intervenciones, enfoque, frecuencia, interconsultas y referencias'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='profesion',
            field=models.TextField(blank=True, verbose_name='Profesión / cargo'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='pronostico',
            field=models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('reservado', 'Reservado'), ('desfavorable', 'Desfavorable')], max_length=100, verbose_name='Pronóstico'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='proxima_cita',
            field=models.TextField(blank=True, verbose_name='Frecuencia de sesiones'),
        ),
    ]
