# Generated by Django 5.2.10 on 2026-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0122_aperturaexpediente_cedula_profesional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='desempeño_escolar',
            field=models.TextField(blank=True, verbose_name='Desempeño escolar, conducta, estructura y dinámica familiar, red de apoyo:'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='otros_signos_vitales',
            field=models.CharField(blank=True, max_length=300, verbose_name='Otro'),
        ),
    ]
