# Generated by Django 5.2.10 on 2026-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0123_aperturaexpediente_desempeño_escolar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='actividad_fisica',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='comidas_al_dia',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='consume_alcohol',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='consume_otras_sustancias',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='cual_actividad_fisica',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='cuales_sustancias',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='fuma',
        ),
        migrations.RemoveField(
            model_name='aperturaexpediente',
            name='horas_sueno',
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='peso_nacer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso y talla al nacer (kg) / APGAR'),
        ),
    ]
