# Generated by Django 5.2.10 on 2026-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0124_remove_aperturaexpediente_actividad_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='diagnostico_previos',
            field=models.TextField(blank=True, verbose_name='Diagnósticos previos hoapitalizaciones psiquiatricas, intentos suicidas/autolesiones, psicoterapias previas'),
        ),
    ]
