# Generated by Django 5.2.10 on 2026-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0125_alter_aperturaexpediente_diagnostico_previos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='diagnosticos_tabla',
            field=models.JSONField(blank=True, null=True, verbose_name='Integración diagnóstica (tabla)'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='estudios_lab',
            field=models.JSONField(blank=True, null=True, verbose_name='Estudios de laboratorio y gabinete'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='instrumentos_neuro',
            field=models.JSONField(blank=True, null=True, verbose_name='Instrumentos neuropsicológicos aplicados'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='instrumentos_psi',
            field=models.JSONField(blank=True, null=True, verbose_name='Instrumentos psicométricos aplicados'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='medicacion_tabla',
            field=models.JSONField(blank=True, null=True, verbose_name='Medicación actual (tabla)'),
        ),
    ]
