# Generated by Django 5.2.10 on 2026-08-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0100_cita_descuento_captacion_porcentaje_snapshot_and_more'),
        ('clinica', '0126_tablas_apertura'),
    ]

    operations = [
    ]
