# Generated by Django 5.2.10 on 2026-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0127_merge_20260821_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='familiar_pareja',
            field=models.TextField(blank=True, verbose_name='Familiar y de pareja'),
        ),
        migrations.AddField(
            model_name='aperturaexpediente',
            name='social_interpersonal',
            field=models.TextField(blank=True, verbose_name='Social / interpersonal'),
        ),
    ]
