# Generated by Django 5.2.10 on 2026-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0128_add_familiar_pareja_social_interpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturaexpediente',
            name='proxima_cita_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Próxima cita'),
        ),
    ]
