# Generated by Django 5.2.10 on 2026-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0129_add_proxima_cita_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='emergencia_contacto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='aperturaexpediente',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Parentesco'),
        ),
    ]
