# Generated by Django 5.2.10 on 2026-09-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0109_alter_cobrocita_options_alter_pago_options'),
        ('clinica', '0130_alter_aperturaexpediente_emergencia_contacto_and_more'),
    ]

    operations = [
    ]
